### ISSUE TITLE
How to import zone

### ISSUE THREAD

**Issue by chriscurnow** [angular-class/angular2-webpack-starter#106]
I'm having a problem with ac-autosuggest.ts.

First off its got the same problem with rx which I know how to fix.

Second though is it tells me "zone" is unknown. I assume this means I need to import zone somehow.

Looking through the various components I can see there is an NgZone in Angular 2.

So I tried changing line 4 to read 

```javascript
import {Directive, View, EventEmitter, ElementRef, NgZone as zone} from 'angular2/angular2';
```

However at runtime, I got into an infinite loop with zone.

I'm not sure where to go from here.

If you could give me a pointer, I'm happy to make the changes and submit a pull request.

**Comment by dotcs** [comment]
I have had a closer look to the problem. The zone object seems available already, which is why you don't need to import it. You just need to make sure, that it Typescript knows the type of the `zone` variable. This can be done with
```javascript
declare var zone: Zone;
```

You can then use it as normal, e.g. in the component
```javascript
onInit() {
  zone.fork({}).run(() => {
    console.log('I am running inside a zone');
  });
  // other code ...
}
```

See also my PR https://github.com/angular-class/angular2-webpack-starter/pull/107 which fixes the rx-autosuggest example.

**Comment by chriscurnow** [comment]
Thanks. That works!!
